/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hackproject;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Ryan
 */
public class assemblerGUI extends javax.swing.JFrame {
    // Private assemblerGUI class fields
    private boolean                 canAssemble;
    private boolean                 canSave;
    private Assembler               hackAssembler;
    private JFileChooser            hackFileChooser;
    private FileNameExtensionFilter hackFilter;
    private FileNameExtensionFilter asmFilter;
    
    /**
     * Creates new form assemblerGUI
     */
    public assemblerGUI() {
        initComponents();
        hackFileChooser = new JFileChooser();
        ImageIcon appIcon = new ImageIcon(getClass().getResource("images/appTopCornerLogo.png")); 
        this.setIconImage(appIcon.getImage());                                      // Change standard application icon in top left corner of window
        canAssemble = false;
        canSave = false;
        asmFilter = new FileNameExtensionFilter("ASM Files", "asm");
        hackFilter = new FileNameExtensionFilter("HACK File", "hack");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asmCodeScrollPane = new javax.swing.JScrollPane();
        asmCodeTextArea = new javax.swing.JTextArea();
        asmCodeLabel = new javax.swing.JLabel();
        hackCodeScrollPane = new javax.swing.JScrollPane();
        hackCodeTextArea = new javax.swing.JTextArea();
        hackCodeLabel = new javax.swing.JLabel();
        assemblerToolBar = new javax.swing.JToolBar();
        openButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        assembleButton = new javax.swing.JButton();
        unloadButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(523, 0), new java.awt.Dimension(553, 0), new java.awt.Dimension(553, 32767));
        aboutButton = new javax.swing.JButton();
        midSeparator = new javax.swing.JSeparator();
        assemblerMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadItem = new javax.swing.JMenuItem();
        saveItem = new javax.swing.JMenuItem();
        fileSeparator = new javax.swing.JPopupMenu.Separator();
        exitItem = new javax.swing.JMenuItem();
        runMenu = new javax.swing.JMenu();
        assembleMenuItem = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenu();
        aboutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hack Assembler");
        setBackground(new java.awt.Color(212, 228, 221));

        asmCodeTextArea.setEditable(false);
        asmCodeTextArea.setColumns(20);
        asmCodeTextArea.setLineWrap(true);
        asmCodeTextArea.setRows(5);
        asmCodeTextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                asmCodeTextAreaCaretUpdate(evt);
            }
        });
        asmCodeScrollPane.setViewportView(asmCodeTextArea);

        asmCodeLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        asmCodeLabel.setForeground(new java.awt.Color(1, 102, 153));
        asmCodeLabel.setText("Assembly Code:");

        hackCodeTextArea.setEditable(false);
        hackCodeTextArea.setColumns(20);
        hackCodeTextArea.setRows(5);
        hackCodeTextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                hackCodeTextAreaCaretUpdate(evt);
            }
        });
        hackCodeScrollPane.setViewportView(hackCodeTextArea);

        hackCodeLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        hackCodeLabel.setForeground(new java.awt.Color(0, 102, 153));
        hackCodeLabel.setText("Assembled Hack Code:");

        assemblerToolBar.setBackground(new java.awt.Color(224, 223, 223));
        assemblerToolBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        assemblerToolBar.setFloatable(false);
        assemblerToolBar.setRollover(true);

        openButton.setBackground(new java.awt.Color(224, 223, 223));
        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackproject/images/opendoc.gif"))); // NOI18N
        openButton.setToolTipText("Open ASM file");
        openButton.setFocusable(false);
        openButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openButton.setMaximumSize(new java.awt.Dimension(50, 50));
        openButton.setMinimumSize(new java.awt.Dimension(32, 32));
        openButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });
        assemblerToolBar.add(openButton);

        saveButton.setBackground(new java.awt.Color(224, 223, 223));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackproject/images/save.png"))); // NOI18N
        saveButton.setToolTipText("Save HACK file");
        saveButton.setEnabled(false);
        saveButton.setFocusable(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setMaximumSize(new java.awt.Dimension(50, 50));
        saveButton.setMinimumSize(new java.awt.Dimension(32, 32));
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        assemblerToolBar.add(saveButton);

        assembleButton.setBackground(new java.awt.Color(224, 223, 223));
        assembleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackproject/images/hex.gif"))); // NOI18N
        assembleButton.setToolTipText("Assembles loaded ASM file to HACK");
        assembleButton.setEnabled(false);
        assembleButton.setFocusable(false);
        assembleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        assembleButton.setMaximumSize(new java.awt.Dimension(50, 50));
        assembleButton.setMinimumSize(new java.awt.Dimension(32, 32));
        assembleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        assembleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assembleButtonActionPerformed(evt);
            }
        });
        assemblerToolBar.add(assembleButton);

        unloadButton.setBackground(new java.awt.Color(224, 223, 223));
        unloadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackproject/images/close.png"))); // NOI18N
        unloadButton.setToolTipText("Unloads current file/data");
        unloadButton.setEnabled(false);
        unloadButton.setFocusable(false);
        unloadButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        unloadButton.setMaximumSize(new java.awt.Dimension(50, 50));
        unloadButton.setMinimumSize(new java.awt.Dimension(32, 32));
        unloadButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        unloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unloadButtonActionPerformed(evt);
            }
        });
        assemblerToolBar.add(unloadButton);
        assemblerToolBar.add(filler1);

        aboutButton.setBackground(new java.awt.Color(224, 223, 223));
        aboutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackproject/images/about.gif"))); // NOI18N
        aboutButton.setToolTipText("About Assembler");
        aboutButton.setFocusable(false);
        aboutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aboutButton.setMaximumSize(new java.awt.Dimension(50, 50));
        aboutButton.setMinimumSize(new java.awt.Dimension(32, 32));
        aboutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });
        assemblerToolBar.add(aboutButton);

        midSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        fileMenu.setText("File");

        loadItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackproject/images/open.gif"))); // NOI18N
        loadItem.setText("Load Assembly File");
        loadItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadItem);

        saveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackproject/images/saveSmall.gif"))); // NOI18N
        saveItem.setText("Save Assembled Hack File");
        saveItem.setEnabled(false);
        saveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveItem);
        fileMenu.add(fileSeparator);

        exitItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exitItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackproject/images/cancel.gif"))); // NOI18N
        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitItem);

        assemblerMenuBar.add(fileMenu);

        runMenu.setText("Run");

        assembleMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackproject/images/hexSmall.png"))); // NOI18N
        assembleMenuItem.setText("Assemble ASM File to Hack Code");
        assembleMenuItem.setEnabled(false);
        assembleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assembleMenuItemActionPerformed(evt);
            }
        });
        runMenu.add(assembleMenuItem);

        assemblerMenuBar.add(runMenu);

        aboutMenu.setText("About");

        aboutItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackproject/images/aboutSmall.gif"))); // NOI18N
        aboutItem.setText("About Hack Assembler");
        aboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutItemActionPerformed(evt);
            }
        });
        aboutMenu.add(aboutItem);

        assemblerMenuBar.add(aboutMenu);

        setJMenuBar(assemblerMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(assemblerToolBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(asmCodeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asmCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(midSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hackCodeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hackCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(assemblerToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hackCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(asmCodeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(asmCodeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                            .addComponent(hackCodeScrollPane)))
                    .addComponent(midSeparator))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadItemActionPerformed
        // Limit file chooser to only show *.asm files /w no 'all files' option
        hackFileChooser.resetChoosableFileFilters();
        hackFileChooser.setFileFilter(asmFilter);
        hackFileChooser.setAcceptAllFileFilterUsed(false);
        hackFileChooser.setSelectedFile(new File("file.asm"));
        
        // Proceed if we selected a file and clicked 'ok'
        if (hackFileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            if(hackFileChooser.getSelectedFile().exists()) {
                File asmFile = hackFileChooser.getSelectedFile();                   // Get file we selected
                hackFileChooser.setCurrentDirectory(asmFile.getParentFile());
                hackAssembler = new Assembler(asmFile);
                hackAssembler.buildSymbolTable();
                asmCodeTextArea.setText(null);                                      // clear text area
                canAssemble = true;
                asmCodeTextArea.setText(hackAssembler.getFileContents());           // Display file contents in text area
            } else {
                JOptionPane.showMessageDialog(this, "FILE ERROR!\nSelected file does not exist!", "Open File Error", JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_loadItemActionPerformed

    private void aboutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutItemActionPerformed
        JOptionPane.showMessageDialog(this, "Hack Assembler\n\nCreated by Ryan MacIntosh\n\n  © 2012 - All Rights Reserved", "Hack Assembler", JOptionPane.OK_OPTION, new ImageIcon(assemblerGUI.class.getResource("images/appTopCornerLogo.png")));
    }//GEN-LAST:event_aboutItemActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitItemActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        loadItemActionPerformed(evt);   // Same event..invoked from toolbar not menu
    }//GEN-LAST:event_openButtonActionPerformed

    private void assembleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assembleMenuItemActionPerformed
        if(asmCodeTextArea.getRows() > 0 && canAssemble) {                          // Make sure load item has run first, and that it contained something to assemble
            hackCodeTextArea.setText(null);                                         // Clear the text area
            canSave = true;
            hackCodeTextArea.setText(hackAssembler.getHackCode());
        } else {
            hackCodeTextArea.setText("There is nothing to assemble!");
        }
        canAssemble = false;
    }//GEN-LAST:event_assembleMenuItemActionPerformed

    private void assembleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assembleButtonActionPerformed
        assembleMenuItemActionPerformed(evt);                                        // Same event..invoked from toolbar not menu
    }//GEN-LAST:event_assembleButtonActionPerformed

    private void asmCodeTextAreaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_asmCodeTextAreaCaretUpdate
        if((asmCodeTextArea.getCaretPosition() != 0) && canAssemble) {
            assembleButton.setEnabled(canAssemble);
            assembleMenuItem.setEnabled(canAssemble);
            unloadButton.setEnabled(true);
        } else {
            if(assembleButton.isEnabled()) {
                canAssemble = false;
                assembleButton.setEnabled(canAssemble);
                assembleMenuItem.setEnabled(canAssemble);
            }
        }
    }//GEN-LAST:event_asmCodeTextAreaCaretUpdate

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        saveItemActionPerformed(evt);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void saveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemActionPerformed
        // Limit file chooser to only show *.asm files /w no 'all files' option
        hackFileChooser.resetChoosableFileFilters();
        hackFileChooser.setFileFilter(hackFilter);
        hackFileChooser.setAcceptAllFileFilterUsed(false);
        hackFileChooser.setSelectedFile(new File(hackAssembler.getFileName() + ".hack"));
        
        boolean doSave = false;
        if(hackFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {   // Didn't cancel out of save dialog window
            doSave = true;
        }

        boolean overrideExistingFile = false;
        File hackSaveFile = new File(hackFileChooser.getSelectedFile().getAbsolutePath());

        while(doSave && hackSaveFile.exists() && !overrideExistingFile) {           // Keep showing save dialog until either overwrite of existing file is confirmed or we provide a different filename
            overrideExistingFile = (JOptionPane.showConfirmDialog(this, "File already exists!\nReplace file?", "Save File", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION);
            if(!overrideExistingFile) {
                if (hackFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                    hackSaveFile = new File(hackFileChooser.getSelectedFile().getAbsolutePath());
                } else {
                    doSave = false;
                }             
            }
        }
        if(doSave) {
            FileWriter fw = null;
            try {
                String filePath = hackSaveFile.getPath();
                if(!filePath.toLowerCase().endsWith(".hack")) {                     // Make sure we save file with the extension of .hack
                    hackSaveFile = new File(filePath + ".hack");
                }
                String hackData = hackCodeTextArea.getText();
                fw = new FileWriter(hackSaveFile);
                fw.write(hackData);
            } catch (IOException ex) {
                Logger.getLogger(assemblerGUI.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    fw.close();
                } catch (IOException ex) {
                    Logger.getLogger(assemblerGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_saveItemActionPerformed

    private void hackCodeTextAreaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_hackCodeTextAreaCaretUpdate
        if((hackCodeTextArea.getCaretPosition() != 0) && canSave) {
            saveButton.setEnabled(canSave);
            saveItem.setEnabled(canSave);
            canAssemble = false;
            assembleButton.setEnabled(canAssemble);
        } else {
            if(saveButton.isEnabled()) {
                canSave = false;
                saveButton.setEnabled(canSave);
                saveItem.setEnabled(canSave);
            }
        }
    }//GEN-LAST:event_hackCodeTextAreaCaretUpdate

    private void unloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unloadButtonActionPerformed
        canSave = false;
        canAssemble = false;
        hackCodeTextArea.setText(null);                                             // Clear the text area
        asmCodeTextArea.setText(null);                                              // Clear the text area
        hackAssembler.unload();
        unloadButton.setEnabled(false);
    }//GEN-LAST:event_unloadButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        aboutItemActionPerformed(evt);
    }//GEN-LAST:event_aboutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(assemblerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(assemblerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(assemblerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(assemblerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new assemblerGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JLabel asmCodeLabel;
    private javax.swing.JScrollPane asmCodeScrollPane;
    private javax.swing.JTextArea asmCodeTextArea;
    private javax.swing.JButton assembleButton;
    private javax.swing.JMenuItem assembleMenuItem;
    private javax.swing.JMenuBar assemblerMenuBar;
    private javax.swing.JToolBar assemblerToolBar;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPopupMenu.Separator fileSeparator;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel hackCodeLabel;
    private javax.swing.JScrollPane hackCodeScrollPane;
    private javax.swing.JTextArea hackCodeTextArea;
    private javax.swing.JMenuItem loadItem;
    private javax.swing.JSeparator midSeparator;
    private javax.swing.JButton openButton;
    private javax.swing.JMenu runMenu;
    private javax.swing.JButton saveButton;
    private javax.swing.JMenuItem saveItem;
    private javax.swing.JButton unloadButton;
    // End of variables declaration//GEN-END:variables
}
